//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clear
    {
        public int ClearId { get; set; }
        [Required(ErrorMessage = "Enter MarketingOpeningDate Required.")]
        [DataType(DataType.DateTime)]
        [Display(Name = "WashRoomClearingDate")]

        public Nullable<System.DateTime> WashRoomClearingDate { get; set; }
        public Nullable<System.DateTime> FilterClearingDate { get; set; }
        public string Notes { get; set; }
        [Display(Name = "MassMemberName")]
        public Nullable<int> MassMemberId { get; set; }
    
        public virtual MassMamber MassMamber { get; set; }
    }
}
