//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Market
    {
        public int MarketId { get; set; }
        [Required(ErrorMessage = "Enter MarketingOpeningDate Required.")]
        [DataType(DataType.DateTime)]
        [Display(Name = "MarketingOpeningDate")]

        public Nullable<System.DateTime> MarketingOpeningDate { get; set; }
        [Required(ErrorMessage = "Enter MarketingCloseingDate Required.")]
        [DataType(DataType.DateTime)]
        [Display(Name = "MarketingCloseingDate")]
        public Nullable<System.DateTime> MarketingCloseingDate { get; set; }
        [Required(ErrorMessage = "Enter Filered Water Required.")]
        [Display(Name = "With Filered Water")]
        public Nullable<bool> Filter { get; set; }
        [Required(ErrorMessage = "Enter boiling Water Required.")]
        [Display(Name = "With boiling Water")]
        public Nullable<bool> Boil { get; set; }
        [Required(ErrorMessage = "Enter MassMarketTk Required.")]
        [Display(Name = "MassMarketTaka")]
        public Nullable<decimal> MarketingTk { get; set; }
        [Required(ErrorMessage = "Enter BigMarketTk Required.")]
        [Display(Name = "BigMarketTaka")]
        public Nullable<decimal> BigMarketingTk { get; set; }
        [Required(ErrorMessage = "Enter TotalTk Required.")]
        [Display(Name = "TotalTaka")]
        public Nullable<decimal> TotalTk { get; set; }
        [Display(Name ="MassMemberName")]
        public Nullable<int> MassMemberId { get; set; }
    
        public virtual MassMamber MassMamber { get; set; }
    }
}
