//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MassMamber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MassMamber()
        {
            this.Clears = new HashSet<Clear>();
            this.Markets = new HashSet<Market>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage ="Enter MassMember Required.")]
        [DataType(DataType.Text)]
        [Display(Name ="MassMemberName")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Enter Your Phone Number Required.")]
        public Nullable<int> PhoneNumber { get; set; }
        [Required(ErrorMessage = "Enter your Email Address Required")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression("^[a-z0-9_\\+-]+(\\.[a-z0-9_\\+-]+)*@[a-z0-9-]+(\\.[a-z0-9]+)*\\.([a-z]{2,4})$", ErrorMessage = "Invalid email format.")]

        public string EmailAddress { get; set; }
        [Required(ErrorMessage = "Enter Your Age Required")]
        [Display(Name="Age")]
        public Nullable<int> Age { get; set; }
        [Required(ErrorMessage = "Enter JoinInDate Required.")]
        [DataType(DataType.DateTime)]
        [Display(Name = "MassMemberJoinInDate")]
        public Nullable<System.DateTime> JoinInDate { get; set; }
        [Display(Name ="DistrictName")]
        [Required(ErrorMessage ="District Name Required")]
        public Nullable<int> DistrictId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clear> Clears { get; set; }
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Market> Markets { get; set; }
    }
}
