//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MassDBEntities : DbContext
    {
        public MassDBEntities()
            : base("name=MassDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clear> Clears { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Market> Markets { get; set; }
        public virtual DbSet<MassMamber> MassMambers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
